# Generated by Django 3.1.6 on 2021-03-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(max_length=80),
        ),
    ]
