# Generated by Django 3.1.6 on 2021-03-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_medicine_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='username',
            new_name='user',
        ),
    ]
